"""
Django settings for grupo4_ProyectoFinal project.

Generated by 'django-admin startproject' using Django 5.2.9.
"""

from pathlib import Path
import os # Necesario para la configuración de Static y Media

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- CONFIGURACIÓN DE RUTAS MODERNAS (Manteniendo la estructura de BASE_DIR)
# Usaremos BASE_DIR para las referencias estáticas/media para mayor claridad.
# La ruta raiz del proyecto es BASE_DIR
# -------------------------------------------------------------------------


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)r=kv6%=kc#yykww4-ra7k5*xv+kgsrqgo%h_l81quu7mx&s)u' # Mantenemos tu SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- Aplicaciones del Grupo (fusionadas) ---
    'apps.autenticacion.apps.AutenticacionConfig', # Tu versión
    'apps.articulos.apps.ArticulosConfig',      # Tu versión completa
    'apps.articulos',                           # Versión corta del grupo (la mantenemos por si acaso)
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'grupo4_ProyectoFinal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], # Tu versión (limpia)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'grupo4_ProyectoFinal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3', # Tu versión (limpia)
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization (Usamos la configuración del grupo para Argentina)

LANGUAGE_CODE = 'es-AR' # Versión del grupo
TIME_ZONE = 'America/Argentina/Buenos_Aires' # Versión del grupo

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# Usamos la configuración de Media y Static del grupo (más completa)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = (BASE_DIR / 'static',)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
